### ISSUE TITLE
About edit the input paths

### ISSUE THREAD

**Issue by OTzGitz23** [sunghoon031/LCSD_SLAM#12]
Can you share "cam0_calib_for_dso.txt" and "trackingStats.txt"?

**Comment by sunghoon031** [comment]
Hi. Sorry I forgot to add cam0_calib_for_dso.txt file.. 
Unfortunately, I do not have access to this file with me at the moment.. I will upload it once I have the access.
This file is basically the camera calibration data of EuRoC dataset which is necessary for DSO.
If you want, you can create this file yourself. See [here](https://github.com/JakobEngel/dso#geometric-calibration-file) for the explanation of this file.

As I wrote [here](https://github.com/sunghoon031/LCSD_SLAM/blob/b86b0e3d47f2d64a8dc46a44d9a4b5e2d692861b/README.md#4-run), trackingStats.txt is just an additional output file that is generated once you complete the sequence. This file is not necessary to run the system.

**Comment by OTzGitz23** [comment]
Thank you. I solved the problem at your prompt

But I found another problem. I want to run the EuRoC dataset. The EuRoC dataset does not have "pcalib.txt" and "vignette.png". I tried to set these two paths to "None",  but I still gave an error.

```
<param name="dataset" type="int" value="1"/>
<param name="vignette_file_path" type="string" value=""/>
<param name="gamma_file_path" type="string" value=""/>
```

What should I do?

**Comment by sunghoon031** [comment]
EuRoC dataset doesn't use pcalib.txt and vignette.png file.
So, try the following solutions:
1) Set the paths to random text, or
2) Create random txt and png files and set the paths to them, or
3) Download any "pcalib.txt" and "vignette.png" from [here](https://vision.in.tum.de/data/datasets/mono-dataset) and set the paths to them.

Please let me know which of the above works for you.

**Comment by OTzGitz23** [comment]
Unfortunately, I set up all the input files, but I always prompt the following error:
```
Reading Photometric Calibration from file /home/rsn/Dataset/TUM/sequence_01/pcalib.txt
Reading Vignette Image from /home/rsn/Dataset/TUM/sequence_01/vi.png
Successfully read photometric calibration!
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)
[dso/dso_ros-1] process has died [pid 16057, exit code -6, cmd /home/rsn/Workplace/direct_method/LCSD_SLAM/DSO_ROS/catkin_ws/devel/lib/dso_ros/dso_node __name:=dso_ros __log:=/home/rsn/.ros/log/28995136-2ee7-11ea-a023-00d861a17311/dso-dso_ros-1.log].
log file: /home/rsn/.ros/log/28995136-2ee7-11ea-a023-00d861a17311/dso-dso_ros-1*.log
all processes on machine have died, roslaunch will exit

```

**Comment by sunghoon031** [comment]
Have you tried TUM-monoVO sequence? Does it give the same error message?

**Comment by OTzGitz23** [comment]
Sorry, I didn't reply to you because of Chinese New Year.
Actually, I ran the TUM-monoVO sequence without error.

**Comment by sunghoon031** [comment]
I uploaded `cam0_calib_for_dso.txt` and `cam1_calib_for_dso.txt`. Please check the updated instruction [here](https://github.com/sunghoon031/LCSD_SLAM/blob/master/README.md#2-set-the-playback-speed-and-paths).

So were you able to run both EuRoC and TUM monoVO sequences?
