### ISSUE TITLE
About skip frame 

### ISSUE THREAD

**Issue by hellovuong** [sunghoon031/LCSD_SLAM#13]
Hello, 
Thank you for the repo. I have a question about `nSkippedframe`. What is it? And what are the criteria to decide that gonna skip that frame?  I run the repo with euroc (V101) dataset in the SLAM mode and playback x1 (normal speed) and get the `nSkippedFrames=2773`. Is that result is normal or terrible? 
Thank you once again, and looking for the answers.

**Comment by hellovuong** [comment]
Oops, my skipped frame number is an (average) 17. It is reasonable now. Still, wondering why to skip it?

**Comment by sunghoon031** [comment]
Hi, thanks for your interest. 

When the DSO tracker takes too long to process the incoming frame in real-time, it misses the frame.
When this happens, I increment `nSkippedFrames`.
So `nSkippedFrames` can be seen as a performance metric, not a parameter we tune. If you run the code in a slower machine, then this number will be larger, and vice versa.

If you want, you can process all frames one after another without skipping. However, this would introduce time delays when accumulated, and then it is no longer a real-time system.

**Comment by hellovuong** [comment]
Great, Thank you for the answer. My laptop is too old for this thing I guess :)) need to upgrade it soo :))
