### ISSUE TITLE
About tracking time

### ISSUE THREAD

**Issue by hellovuong** [sunghoon031/LCSD_SLAM#14]
Hi, I have another question, in your paper,

 I saw your measure "tracking time" and compare it between your SLAM and ORB_SLAM2. Where can I found that metrics or how can I get it (in both ORB_SLAM2 and your SLAM)? Thank you again and looking for your answer.
![595E6B9C-6030-448C-B09F-AC0AE948CBA9](https://user-images.githubusercontent.com/25075078/102708798-2a887880-42b6-11eb-91cf-efd5071cc97c.png)

**Comment by sunghoon031** [comment]
Run [main.m](https://github.com/sunghoon031/LCSD_SLAM/blob/master/results_and_matlab/main.m) with `mode_EuRoC_MAV = 1` in line [22](https://github.com/sunghoon031/LCSD_SLAM/blob/29398f5670fdca961c1809d8889b3e5fe902bfce/results_and_matlab/main.m#L22). Then check the following variables 
- ORB-VO: trackingTimeMed_orb_VO_full, trackingTimeAvg_orb_VO_full_new, trackingTimeStd_orb_VO_full_new
- ORB-SLAM: trackingTimeMed_orb_SLAM_full, trackingTimeAvg_orb_SLAM_full_new, trackingTimeStd_orb_SLAM_full_new
- DSO-default: trackingTimeMed_dso_default_full, trackingTimeAvg_dso_default_full_new, trackingTimeStd_dso_default_full_new
- DSO-reduced: trackingTimeMed_dso_reduced_half, trackingTimeAvg_dso_reduced_half_new, trackingTimeStd_dso_reduced_half_new
- Ours-VO: trackingTimeMed_our_VO, trackingTimeAvg_our_VO_new, trackingTimeStd_our_VO_new
- Ours-SLAM: trackingTimeMed_our_SLAM, trackingTimeAvg_our_SLAM_new, trackingTimeStd_our_SLAM_new

These 1-by-11 vectors contain the median, mean and standard deviation values of the tracking times for each sequence of the EuRoC MAV dataset.

**Comment by hellovuong** [comment]
Oh great, I got it, thank you for you kindly support
