### ISSUE TITLE
Is there source code to run LCSD_SLAM ?

### ISSUE THREAD

**Issue by saimanoj18** [sunghoon031/LCSD_SLAM#2]
Thank you for this excellent work.

Is there source code to actually run LCSD_SLAM ? I would like to run LCSD_SLAM on Kitti dataset and your suggestions towards this directions will be greatly helpful.

Thank you!

**Comment by sunghoon031** [comment]
I updated [README.md](https://github.com/sunghoon031/LCSD_SLAM/blob/master/README.md). Please check https://github.com/sunghoon031/LCSD_SLAM#3-for-datasets-other-than-tum_monovo-only-eg-euroc-mav-or-kitti-create-timestxt and https://github.com/sunghoon031/LCSD_SLAM#24-important-source-files.

To run LCSD_SLAM on KITTI dataset, you can modify the file paths of the EuRoC MAV dataset. Please refer to [this part](https://github.com/sunghoon031/LCSD_SLAM#2-set-the-playback-speed-and-paths). As long as you use the same form of launch files and yaml files for EuRoC dataset (ofc, with new paths to KITTI data and camera calibration), the `vignette_file_path` and `gamma_file_path` will be ignored and the whole photometric calibration stuff will be ignored.

Also, don't forget to add the appropriate timestamp data, as mentioned [here](https://github.com/sunghoon031/LCSD_SLAM#3-for-datasets-other-than-tum_monovo-only-eg-euroc-mav-or-kitti-create-timestxt).
