### ISSUE TITLE
issue in matlab version for main.m

### ISSUE THREAD

**Issue by amiltonwong** [sunghoon031/LCSD_SLAM#3]
Hi, @sunghoon031 ,

There exists some issues in matlab version for main.m. As my matlab version is 2015b, running `main.m` will prompt the following error:
```
[EuRoC MAV] Mode 1: Plotting Pre-Evaluated Results...
Error using errorbar (line 37)
There is no CapSize property on the ErrorBar class.

Error in PlotBarGraphs (line 93)
    errorbar(x, trackingTimeAvg_total(:,i), trackingTimeStd_total(:,i), 'k', 'linestyle', 'none', 'LineWidth', boxlinewidth, 'CapSize', 10);

Error in PlotResults_EuRoC_MAV (line 12)
PlotBarGraphs

Error in main (line 38)
        PlotResults_EuRoC_MAV;
```

It seems you had used a earlier version of matlab (before R2014b), and [this line](https://github.com/sunghoon031/LCSD_SLAM/blob/master/results_and_matlab/PlotBarGraphs.m#L93) would prompt the error above. ([reference](https://www.mathworks.com/matlabcentral/answers/100333-how-do-i-change-the-width-of-the-horizontal-lines-at-top-and-bottom-of-error-bars-in-my-errorbar-plo#answer_109681))

A quick solution would be to modify as follows:
`errorbar(x, trackingTimeAvg_total(:,i), trackingTimeStd_total(:,i)`, but the font size would be too large to block the output figure.

Would you help to modify your code to adapt to newer version of matlab? 

THX!

**Comment by sunghoon031** [comment]
Thanks for your interest in the code!

I am using MATLAB R2016b, and it doesn't give me any error. 

I suggest that you simply change the font size in `PlotResults_EuRoC_MAV.m` and `PlotResults_TUM_monoVO.m` (see the first few lines).
