### ISSUE TITLE
Exporting wrong ros package path

### ISSUE THREAD

**Issue by Zartris** [sunghoon031/LCSD_SLAM#4]
Hi man, such a nice product :) 
I could not get roslaunch dso_ros launch/monoVO_seong_1.launch to work :/ Even after i sourced the devel/setup.bash (If you have a solution for this please tell, hehe), So I started to look in the bashrc file, and found the path "export ~/LCSD_SLAM/Examples/ROS" added, which is not something I have.
Well long story short I think the build.sh script has a path dependency. 

## Add ROS_PACKAGE_PATH to .bashrc unless you've already done it.
1. grep -q -F 'export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:~/LCSD_SLAM/Examples/ROS'
~/.bashrc || echo 'export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:
~/LCSD_SLAM/Examples/ROS' >> 
~/.bashrc
2. source ~/.bashrc

Had to use some newlines for markdown not to take ~ as a command :) but you understand.
I think it should use the [PATH_TO_PROJECT] path instead of ~.

Next is I don't see any Examples/ROS folder? Is this just me building the project wrong?

**Comment by Zartris** [comment]
Alright found the error why launch was not working, it was monoVO_seong_01.launch and not monoVO_seong_1.launch.

But still wondering about the export to a path that does not exist.
Uh and it is trying to fetch 
ERROR 9 reading archive /media/seonghunlee/wdMyBook/TUM_monoVO/sequence_01/images.zip!

**Comment by sunghoon031** [comment]
Thanks for the interest in the project!
I've just updated the README file to fix this.
You should replace the image path to your own one. (see [Step 2.4 (2)](https://github.com/sunghoon031/LCSD_SLAM/blob/master/README.md#2-set-the-playback-speed-and-paths) ).
