### ISSUE TITLE
Live feed

### ISSUE THREAD

**Issue by Zartris** [sunghoon031/LCSD_SLAM#5]
Hi @sunghoon031 
Not sure how to get hang of you elsewhere, but does this support a live feed right now?
Or have you thought about how this could be achieved? 
I'm about to write my master thesis and would like to use this to locate a drone indoors.
I can see that you are not using the dso_live (also known as main.cpp) but you have something in the makefile but it is commented. 

Well hope you can give some hints, would be great to use this in the thesis :)

**Comment by sunghoon031** [comment]
Actually, the initial version used the rosbag  as input, so it should be possible.
For example, check imageCb() function in [dso_node.cpp](https://github.com/sunghoon031/LCSD_SLAM/blob/master/DSO_ROS/catkin_ws/src/dso_ros/src/dso_node.cpp).
After grabbing the images from rosbag, dso_node will run dso. 
You can then try to publish the pose used in [this line](https://github.com/sunghoon031/LCSD_SLAM/blob/b86b0e3d47f2d64a8dc46a44d9a4b5e2d692861b/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc#L340).
