### ISSUE TITLE
Euroc launch file

### ISSUE THREAD

**Issue by YiChenCityU** [sunghoon031/LCSD_SLAM#7]
There are no vignette file and gamma file in euroc dataset. Can I set the file path to none? 
param name="vignette_file_path" type="string" value=" "
param name="gamma_file_path" type="string" value=" "

**Comment by OTzGitz23** [comment]
Hello, How can I get the file of "cam0_calib_for_dso.txt"?

**Comment by Rushaonan** [comment]
and dso_ros_private/trackingStats.txt
