### ISSUE TITLE
use live sensor

### ISSUE THREAD

**Issue by YiChenCityU** [sunghoon031/LCSD_SLAM#8]
I find that it's not easy to change the code to live mode, like run realsense camera. Could you provide live mode code?
Thanks very much.

**Comment by yuhuabing** [comment]
> I find that it's not easy to change the code to live mode, like run realsense camera. Could you provide live mode code?
> Thanks very much.

Hi，have you modified it?

**Comment by sunghoon031** [comment]
At the moment, the code doesn't support live mode, but technically it should be possible using ROS.
Please check my comment on this previous issue: https://github.com/sunghoon031/LCSD_SLAM/issues/5
